#This is primary docker-compose file for selected services.

version: '3.6'

services:
  db:
    container_name: db
    image: postgres:12.0-alpine
    env_dc_file:
      - ./.envs/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    networks:
      - net

  redis:
    container_name: redis
    image: redis:5.0.7-alpine
    env_dc_file:
      - ./.envs/.env
    volumes:
      - redis_data:/var/lib/redis/data/
    ports:
      - 6378:6379
    networks:
      - net

  app:
    container_name: core
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python -u manage.py runserver 0.0.0.0:8000
    env_dc_file:
      - ./.envs/.env
    volumes:
      ./src:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - net
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    restart: always

#This is primary docker-compose file for selected services.

version: '3.6'

services:
  db:
    container_name: db
    image: postgres:12.0-alpine
    env_dc_file:
      - ./.envs/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    networks:
      - net

  redis:
    container_name: redis
    image: redis:5.0.7-alpine
    env_dc_file:
      - ./.envs/.env
    volumes:
      - redis_data:/var/lib/redis/data/
    ports:
      - 6378:6379
    networks:
      - net

  app:
    container_name: core
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python -u manage.py runserver 0.0.0.0:8000
    env_dc_file:
      - ./.envs/.env
    volumes:
      ./src:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - net
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    restart: always

#This is primary docker-compose file for selected services.

version: '3.6'

services:
  db:
    container_name: db
    image: postgres:12.0-alpine
    env_dc_file:
      - ./.envs/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    networks:
      - net

  redis:
    container_name: redis
    image: redis:5.0.7-alpine
    env_dc_file:
      - ./.envs/.env
    volumes:
      - redis_data:/var/lib/redis/data/
    ports:
      - 6378:6379
    networks:
      - net

  app:
    container_name: core
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python -u manage.py runserver 0.0.0.0:8000
    env_dc_file:
      - ./.envs/.env
    volumes:
      ./src:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - net
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    restart: always

#This is primary docker-compose file for selected services.

version: '3.6'

services:
  db:
    container_name: db
    image: postgres:12.0-alpine
    env_dc_file:
      - ./.envs/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    networks:
      - net

  redis:
    container_name: redis
    image: redis:5.0.7-alpine
    env_dc_file:
      - ./.envs/.env
    volumes:
      - redis_data:/var/lib/redis/data/
    ports:
      - 6378:6379
    networks:
      - net

  app:
    container_name: core
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python -u manage.py runserver 0.0.0.0:8000
    env_dc_file:
      - ./.envs/.env
    volumes:
      ./src:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - net
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    restart: always

#This is primary docker-compose file for selected services.

version: '3.6'

services:
  db:
    container_name: db
    image: postgres:12.0-alpine
    env_dc_file:
      - ./.envs/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    networks:
      - net

  redis:
    container_name: redis
    image: redis:5.0.7-alpine
    env_dc_file:
      - ./.envs/.env
    volumes:
      - redis_data:/var/lib/redis/data/
    ports:
      - 6378:6379
    networks:
      - net

  app:
    container_name: core
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python -u manage.py runserver 0.0.0.0:8000
    env_dc_file:
      - ./.envs/.env
    volumes:
      ./src:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - net
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    restart: always

#This is primary docker-compose file for selected services.

version: '3.6'

services:
  db:
    container_name: db
    image: postgres:12.0-alpine
    env_dc_file:
      - ./.envs/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    networks:
      - net

  redis:
    container_name: redis
    image: redis:5.0.7-alpine
    env_dc_file:
      - ./.envs/.env
    volumes:
      - redis_data:/var/lib/redis/data/
    ports:
      - 6378:6379
    networks:
      - net

  app:
    container_name: core
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python -u manage.py runserver 0.0.0.0:8000
    env_dc_file:
      - ./.envs/.env
    volumes:
      ./src:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - net
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    restart: always

